version: '3.3'

services:

  db:
    container_name: pazartierp_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pazartierp_db
    env_file:
      - env/dev.env
    image: postgres:15-alpine
    expose:
      - "5432"
    ports:
      - "5455:5432"
    volumes:
#      Linux
#      - /home/data/pazartidb:/var/lib/postgresql/data:rw
#      Local Mac
      - /Users/user/data/pazartierpdb:/var/lib/postgresql/data:rw
#
#  web:
#    container_name: pazarti_web
#    env_file:
#      - core/etc/dev.env
#    build: .
#    volumes:
#      - .:/app
#    depends_on:
#      - redis
#    expose:
#      - "8000"
#    ports:
#      - "8005:8000"
#
#  celery:
#    env_file:
#      - config/etc/dev.env
#    build:
#      context: .
#    container_name: pazartierp_celery
#    command: celery -A core worker -c 3 --loglevel=info
#    volumes:
#      - .:/app
#    depends_on:
#      - redis

#  celery-beat:
#    env_file:
#      - config/etc/dev.env
#    build:
#      context: .
#    container_name: pazartierp_celery-beat
#    command: celery -A core beat --loglevel=info
#    volumes:
#      - .:/app
#    depends_on:
#      - redis
#      - celery
#
#  redis:
#    image: "redis:alpine"
#    container_name: redis
#    ports:
#      - "6379:6379"

#  nginx:
#    container_name: pazarti_nginx
#    env_file:
#      - core/etc/dev.env
#    image: nginx
#    ports:
#      - "443:443"
#    volumes:
#      - ./core/etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
#      - ./core/etc/nginx/certs/public.pem:/etc/nginx/ssl/live/certs/public.pem
#      - ./core/etc/nginx/certs/private.pem:/etc/nginx/ssl/live/certs/private.pem
#      - ./staticfiles:/pazarti/staticfiles
#      - ./media:/pazarti/media
#    depends_on:
#      - web