version: '3.3'

services:

  db:
    container_name: pazartierp_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pazartierp_db
    env_file:
      - env/dev.env
    image: postgres:15-alpine
    expose:
      - "5432"
    ports:
      - "5455:5432"
    volumes:
#      Linux
#      - /home/data/pazartidb:/var/lib/postgresql/data:rw
#      Local Mac
      - /Users/user/data/pazartierpdb:/var/lib/postgresql/data:rw
