# Generated by Django 5.0.3 on 2025-02-19 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currencyrate",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.org",
                verbose_name="Org",
            ),
        ),
        migrations.AlterField(
            model_name="usersetting",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.org",
                verbose_name="Org",
            ),
        ),
    ]
